repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run Pytest Before Commit
        entry: poetry run python -m pytest tests/test_api.py
        language: system
        pass_filenames: false
