repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run Pytest Before Commit
        # here test only api
        entry: poetry run pytest tests/test_api.py
        language: system
        pass_filenames: false