services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
      POSTGRES_DB: fitness
    ports:
      - "5432:5432"
    volumes:
      - /tmp/db_data:/var/lib/postgresql/data # Changed path to /tmp
      #- ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m api
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m bot
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  redis_data:
