"""Add subSummary

Revision ID: 55abc90e848f
Revises: d2f8b0a76127
Create Date: 2025-03-30 17:30:54.302965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55abc90e848f'
down_revision: Union[str, None] = 'd2f8b0a76127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_summaries_id'), 'sub_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_sub_summaries_telegram_id'), 'sub_summaries', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_summaries_telegram_id'), table_name='sub_summaries')
    op.drop_index(op.f('ix_sub_summaries_id'), table_name='sub_summaries')
    op.drop_table('sub_summaries')
    # ### end Alembic commands ###
