"""Make telegram_id unique

Revision ID: d2f8b0a76127
Revises: 216716d73576
Create Date: 2025-03-21 10:43:51.147236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f8b0a76127'
down_revision: Union[str, None] = '216716d73576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_telegram_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_telegram_id_fkey', 'messages', 'users', ['telegram_id'], ['id'])
    # ### end Alembic commands ###
