llm_provider: "none"  # Options: google, openai, yandex or none (for debugging)
google:
  model: "gemini-2.0-flash"
  api_key_env: "GOOGLE_API_KEY"

openai:
  model: "gpt-4"
  api_key_env: "OPENAI_API_KEY"

yandex:
  model: "yandexgpt-lite"
  folder_id_env: "FOLDER_ID"
  api_key_env: "YANDEX_API_KEY"
